
const BACKGROUND_COLOR = "#faf9f7";

const CUSTOM_GRADIENT_COLOR = "linear-gradient(to right, #1F85B2, #69AF74)";

const LIGHT_GREY_COLOR = "#B4B4B4";

const LIGHT_GREY_DESCRIPTION = "#989898";

const DARk_GREY_COLOR = "#6E6E5E";






export {BACKGROUND_COLOR, CUSTOM_GRADIENT_COLOR , LIGHT_GREY_COLOR, DARk_GREY_COLOR, LIGHT_GREY_DESCRIPTION}