const BACKGROUND_COLOR = "#faf9f7";

// const LIGHT_BACKGROUND_COLOR = "#f6f7fa";
const LIGHT_BACKGROUND_COLOR = "rgb(248, 248, 248)";

const CUSTOM_GRADIENT = "linear-gradient(-140deg, #268a59, #0087b2)";

const CUSTOM_SUNRISE_GRADIENT_COLOR = "linear-gradient(-140deg, #FF5F6D, #FFC371)";

const CUSTOM_GRADIENT_COLOR = "linear-gradient(-140deg, #e96443, #904e95)";

const LIGHT_GREY_COLOR = "#B4B4B4";

const LIGHT_GREY_DESCRIPTION = "#989898";

const DARk_GREY_COLOR = "#6E6E5E";

const DESCRIPTION_COLOR = "#8492a6";

const DESCRIPTION_COLOR_LIGHT = "#bdb9bb";

const LABEL_COLOR = "#989898";

const TITLE_COLOR = "#004483";

const SECTION_TITLE_COLOR = "#161c2d"

export {
  CUSTOM_GRADIENT,
  CUSTOM_SUNRISE_GRADIENT_COLOR,
  LIGHT_BACKGROUND_COLOR,
  SECTION_TITLE_COLOR,
  DESCRIPTION_COLOR_LIGHT,
  LABEL_COLOR,
  BACKGROUND_COLOR,
  CUSTOM_GRADIENT_COLOR,
  LIGHT_GREY_COLOR,
  DARk_GREY_COLOR,
  LIGHT_GREY_DESCRIPTION,
  DESCRIPTION_COLOR,
  TITLE_COLOR,
};
